def fun():
	return 1
	raise Exception("B")


print(fun())